### ISSUE TITLE
Linux Houdini 14 vers

### ISSUE THREAD

**Issue by sainthk** [ThinkboxSoftware/HoudiniPRTExporter#1]
any update for houdini14 or 15?

**Comment by MarcAntoine-Arnaud** [comment]
I've done it for Houdini 14. I can update it soon.

**Comment by RandomInsano** [comment]
That sounds good to me! Let me know if/when I need to poke our guys here to review.

**Comment by paulrondeau** [comment]
What version of Houdini are you using now?

We just added new builds for Houdini 16.  Please let us know if you need a build for some other version!
